### ISSUE TITLE
Should device memory be limited to what the UA can access?

### ISSUE THREAD

**Issue by bzbarsky** [WICG/device-ram#13]
What should happen in cases when the UA does not have access to all the physical memory on the device?  Most simply, 32-bit UA on a system with more than 4GB of RAM.

**Comment by spanicker** [comment]
Yes it makes sense to limit to what the UA can possibly access.
I'll update the spec to indicate that

**Comment by spanicker** [comment]
App should be able to distinguish between the case where the UA is actually reporting the max value (because that is the total memory) vs. falling into the overflow bucket, so maybe a special number should be reported for the latter - eg. -1?

@fmeawad @igrigorik @domenic  - thoughts?

**Comment by fmeawad** [comment]
My concern is that this API is meant to give web developers an approximation of the device class based on its memory capacity and not how much memory they can actually use. A 64 GB device with an application using 63 GB is no different from a 2 GB device with only the UA running.

But, in most cases the UA will get more resources if the device has more resources and hence the purpose of the API.

If the device memory is > accessible memory by the UA, I would argue that we should report the device memory as is. If we truncate to accessible, then we should use the max accessible value instead of -1. As this would provide a value that web developers can programatically use.

I also believe that the web developers can figure out if they are running on a 32 bit system from the user-agent string.

**Comment by domenic** [comment]
Agreed with @fmeawad. If you do -1 I think people will just assume the device has very low memory available.

**Comment by spanicker** [comment]
Makes sense to me.

**Comment by yoavweiss** [comment]
So, seems like the discussion here converged on not exposing the accessible memory, but the overall device one, right?

If so, can we close?
